### ISSUE TITLE
seral flasher stops responding if MD5 included (ESF-22)

### ISSUE THREAD

**Issue by JeffreyEWright** [espressif/esp-serial-flasher#51] opened 2022-12-09 20:16 UTC
Hello;
I've implemented the example on my client's STM32L431, and I can successfully flash the bootloader, partition table, and application via UART0.  However, IF I include the MD5 checksum, [b]it stops responding after I flash the bootloader partition[/b]??
The response after send_cmd_md5() is odd, since command is returned as [i]0x24[/i], but should be 0x13. Nevertheless, the correct MD5 checksum appears to be returned correctly, BUT it is [i]shifted by one byte[/i], with the first byte being written at "response.common.value"...is the 0x24 command valid?...If so, I cannot find any documentation to explain its meaning?

SO, any help would be greatly appreciated!

c0 01 [b][i][color=#FF0000]24[/color][/i][/b] 00 20 40 16 00 37 33 65 38 38 62 35 63 33 37 65 63 39 30 36 30 64 66 35 33 30 39 65 63 39 31 38 34 65 34 33 64 00 00 00 00 c0

Thanks.

**Comment by dobairoland** [comment] 2022-12-10 06:35
Duplicate of #52

**Closed by dobairoland** 2022-12-10 06:35 UTC
