### ISSUE TITLE
When the serial port upgrade program goes to esp_loader_flash_start->detect_flash_size, it returns ESP_LOADER_ERROR_TIMEOUT error  (ESF-13)

### ISSUE THREAD

**Issue by didyoudo** [espressif/esp-serial-flasher#41] opened 2022-07-04 10:01 UTC
I use esp32c3_MINI-1 module, on linux platform

After the connection between my development board and the esp32c3 module is established, and the baud rate of both parties is successfully modified to 921600, the new data in the serial port cannot be obtained in the esp_loader_read_register interface.

The following is the log when I test：

------>s_target = 3
Connected to target

--- WRITE ---
c0 
00 0f 08 00 00 00 00 00 00 10 0e 00 00 00 00 00 
c0 
------->send cmd size = 16
---->read bytesToRead=0---fd=3

--- READ ---
c0 
---->read bytesToRead=15---fd=3
01 
---->read bytesToRead=14---fd=3
0f 
---->read bytesToRead=13---fd=3
04 
---->read bytesToRead=12---fd=3
00 
---->read bytesToRead=11---fd=3
00 
---->read bytesToRead=10---fd=3
00 
---->read bytesToRead=9---fd=3
00 
---->read bytesToRead=8---fd=3
00 
---->read bytesToRead=7---fd=3
00 
---->read bytesToRead=6---fd=3
00 
---->read bytesToRead=5---fd=3
00 
---->read bytesToRead=4---fd=3
00 
---->read bytesToRead=3---fd=3
c0 
------>loader_port_change_baudrate serial fd=3
modify baudrate=921600, waiting...
modify baudrate=921600, waiting...
modify baudrate=921600, waiting...
modify baudrate=921600, waiting...
modify baudrate=921600, waiting...
Baudrate changed
esp32c3 upgrade firmware status = 1, progress = 0
Enter esp32c3 BLE update flowing...

****************************************
sub imgName: 6
sub imgLen: 982720
sub imgVer: 1656568426
****************************************
Erasing flash (this may take a while)...
---------->11111111

--- WRITE ---
c0 
00 0a 04 00 00 00 00 00 18 20 00 60 
c0 
------->send cmd size = 12
---->read bytesToRead=2---fd=3

--- READ ---
c0 
---->read bytesToRead=1---fd=3
c0 
---->read bytesToRead=0---fd=3
esp32c3 upgrade firmware status = 2, progress = 0
DEBUG: Flash size detection failed, falling back to default

--- WRITE ---
c0 
00 02 14 00 00 00 00 00 00 00 0f 00 
db dc 
03 00 00 00 04 00 00 00 00 06 00 00 00 00 00 
c0 
------->send cmd size = 28
---->read bytesToRead=0---fd=3
esp32c3 upgrade firmware status = 2, progress = 0
esp32c3 upgrade firmware status = 2, progress = 0
esp32c3 upgrade firmware status = 2, progress = 0
esp32c3 upgrade firmware status = 2, progress = 0
esp32c3 upgrade firmware status = 2, progress = 0
esp32c3 upgrade firmware status = 2, progress = 0
esp32c3 upgrade firmware status = 2, progress = 0
esp32c3 upgrade firmware status = 2, progress = 0
esp32c3 upgrade firmware status = 2, progress = 0
esp32c3 upgrade firmware status = 2, progress = 0
Erasing flash failed with error 2.

**Comment by DNedic** [comment] 2023-04-25 12:24
Thank you for your submission, I have managed to reproduce the issue. 

Could you try flashing without the baudrate change, at 115200 until the issue is fixed?

**Comment by didyoudos** [comment] 2023-04-25 14:01
> 

Thanks for your reply.

I am using a 32-bit cpu with ARM architecture and configuring the serial port parameters according to the _serialOpen_ function in _esp-serial-flasher/port/raspberry_port.c_. The hardware connection is using UART0 of ESP32C3 and the serial port of CPU (just RX-TX-GND) ;

I enter the download mode of esp32c3 through CHIP_EN and RST pins, after successfully entering the download mode and the CPU successfully establishes a connection with ESP32C3 using 115200 baud rate.

**Now the exception**:  after the CPU sends cmd to change the baud rate, ESP32C3 replies successfully, and the last two bytes "0xC0, 0xC0", then the CPU sends cmd to ESP32C3 again, ESP32C3 has no reply.

NOTE: If the CPU does not send a command to change baud rate to the ESP32C3 module during the upgrade process, then the upgrade process will successfully upgrade at 115200 baud rate; however, if the baud rate is modified, either to a higher baud rate or a lower one, such as 460800 or 9600, the above upgrade exception will occur.

**Comment by didyoudos** [comment] 2023-04-26 07:04
> Thank you for your submission, however I could not manage to reproduce the issue.
> 
> What is your board setup, and could you try flashing at 115200? As UART is an asynchronous protocol, higher baudrates can be unstable due to factors like clock drift or jitter.

If you still can't reproduce the issue, then I wonder if your host and ESP32C3 module UART0 port still have a USB-to-serial port module? Try removing the USB-to-serial port module and connect the host and ESP32C3's UART0 with only RX-TX-GND.

**Comment by dobairoland** [comment] 2023-04-28 06:33
![IMG_20230428_083018_4](https://user-images.githubusercontent.com/3954250/235072038-dd597467-90da-4328-b4e8-1efc67f8dbb0.jpg)

Here is our setup. The board is power directly from the RPI and the USB connection is not used.

**Comment by dobairoland** [comment] 2023-04-28 06:36
> If you still can't reproduce the issue, then I wonder if your host and ESP32C3 module UART0 port still have a USB-to-serial port module? Try removing the USB-to-serial port module and connect the host and ESP32C3's UART0 with only RX-TX-GND.

Do you mean that you have a custom board? If you have an ESP32-C3 standard devkit as well then could you try it with that?

Have you considered that maybe your TxD and RxD lines too long or noisy?

**Comment by dobairoland** [comment] 2023-05-29 11:57
I'm closing this because we cannot reproduce it and cannot proceed without additional information.

**Closed by dobairoland** 2023-05-29 11:57 UTC
